// Recipes. Quantities are for ONE portion, raw/dry weights, and are only a
// starting point: the planner rescales the 'protein' and 'carb' ingredients to
// your calorie and protein targets for each meal.
//
// role: protein | carb   -> rescaled
//       veg | fruit | fat | season -> kept as written (gut-friendly portions)
// minPhase on an ingredient: it is left out in earlier phases.

const R = (recipe) => ({ batch: false, tags: [], tips: [], ...recipe });

export const RECIPES = [
  // ───────────── Breakfast ─────────────
  R({
    id: 'eggs_toast_fruit',
    name: 'Ovos mexidos com torradas e fruta',
    en: 'Scrambled eggs on toast with fruit',
    slots: ['breakfast'],
    phase: 1,
    methods: ['pan'],
    minutes: 10,
    ingredients: [
      { food: 'eggs', g: 104, role: 'protein' },
      { food: 'egg_whites', g: 100, role: 'protein' },
      { food: 'bread', g: 56, role: 'carb' },
      { food: 'banana', g: 120, role: 'fruit' },
      { food: 'olive_oil', g: 3, role: 'fat' },
      { food: 'chives', g: 2, role: 'season' },
    ],
    steps: [
      'Whisk the eggs and egg whites with a pinch of salt.',
      'Heat a non-stick pan on medium-low with the measured oil (spread it with kitchen paper).',
      'Pour in the eggs and stir slowly with a spatula for 2–3 min until just set. Take off the heat while still slightly glossy.',
      'Toast the bread. Top the eggs with chopped chives (green part only).',
      'Eat the fruit on the side.',
    ],
    tips: ['No liquid egg whites? Use 1 more whole egg instead of every 100 g of whites.'],
    gut: 'Gentle, low-fibre start to the day. Chives give flavour without onion.',
  }),
  R({
    id: 'turkey_egg_toast',
    name: 'Tosta de fiambre de peru e ovo',
    en: 'Turkey ham & egg toast',
    slots: ['breakfast'],
    phase: 1,
    methods: ['pan'],
    minutes: 8,
    ingredients: [
      { food: 'eggs', g: 104, role: 'protein' },
      { food: 'turkey_ham', g: 60, role: 'protein' },
      { food: 'bread', g: 56, role: 'carb' },
      { food: 'kiwi', g: 75, role: 'fruit' },
      { food: 'olive_oil', g: 2, role: 'fat' },
    ],
    steps: [
      'Fry or scramble the eggs in a non-stick pan with the measured oil (2–3 min).',
      'Toast the bread and fill it with the turkey ham and eggs.',
      'Have the kiwi on the side.',
    ],
    tips: ['Read the ham label: pick one with no "lactose", "leite em pó", "cebola" or "alho".'],
    gut: 'Kiwi is gentle fruit that helps keep things regular.',
  }),
  R({
    id: 'oat_porridge_whites',
    name: 'Papas de aveia com claras, banana e canela',
    en: 'Oat porridge with egg whites, banana & cinnamon',
    slots: ['breakfast'],
    phase: 2,
    methods: ['saucepan'],
    minutes: 10,
    ingredients: [
      { food: 'oats', g: 40, role: 'carb' },
      { food: 'egg_whites', g: 150, role: 'protein' },
      { food: 'banana', g: 60, role: 'fruit' },
      { food: 'peanut_butter', g: 10, role: 'fat' },
      { food: 'cinnamon', g: 1, role: 'season' },
    ],
    steps: [
      'Bring the oats and 250 ml water to the boil with a pinch of salt; simmer 3–4 min, stirring.',
      'Lower the heat and slowly whisk in the egg whites. Keep stirring 1–2 min until thick and fluffy (cook until no liquid white is left).',
      'Top with sliced banana, the peanut butter and cinnamon.',
    ],
    tips: ['Start with 30 g oats if fibre is new to you, then build up.', 'Microwave: 2 min, stir, add whites, 1–2 min more in 30 s bursts.'],
    gut: 'Oats give soluble fibre, the kind that is usually well tolerated and firms stools.',
  }),
  R({
    id: 'banana_oat_pancakes',
    name: 'Panquecas de banana e aveia',
    en: 'Banana & oat pancakes',
    slots: ['breakfast'],
    phase: 2,
    methods: ['pan'],
    minutes: 15,
    ingredients: [
      { food: 'banana', g: 120, role: 'fruit' },
      { food: 'eggs', g: 104, role: 'protein' },
      { food: 'egg_whites', g: 100, role: 'protein' },
      { food: 'oats', g: 35, role: 'carb' },
      { food: 'olive_oil', g: 3, role: 'fat' },
      { food: 'strawberries', g: 80, role: 'fruit', minPhase: 2 },
      { food: 'cinnamon', g: 1, role: 'season' },
    ],
    steps: [
      'Mash the banana with a fork, whisk in the eggs, egg whites, oats and cinnamon (or blend everything).',
      'Heat a non-stick pan on medium-low, wipe with the measured oil.',
      'Cook small pancakes (2 tablespoons of batter) for 2 min per side until set.',
      'Serve with the strawberries.',
    ],
    tips: ['Batter keeps 1 day in the fridge.'],
    gut: 'No sweeteners, no dairy.',
  }),

  // ───────────── Lunch & dinner ─────────────
  R({
    id: 'chicken_rice_carrots',
    name: 'Frango no air fryer com arroz e cenoura',
    en: 'Air-fryer chicken with rice & carrots',
    slots: ['lunch', 'dinner'],
    phase: 1,
    methods: ['air fryer', 'saucepan'],
    minutes: 25,
    batch: true,
    ingredients: [
      { food: 'chicken_breast', g: 170, role: 'protein' },
      { food: 'rice_white', g: 70, role: 'carb' },
      { food: 'carrots', g: 120, role: 'veg' },
      { food: 'olive_oil', g: 5, role: 'fat' },
      { food: 'lemon', g: 10, role: 'season' },
      { food: 'paprika', g: 1, role: 'season' },
      { food: 'oregano', g: 1, role: 'season' },
    ],
    steps: [
      'Rice: rinse it in a sieve. Boil twice its volume of salted water, add the rice, cover and simmer on low for 12–14 min. Rest 5 min off the heat.',
      'Carrots: peel, slice into coins and boil or steam 10–12 min until soft.',
      'Chicken: pat dry and rub with the measured oil, colorau (paprika), oregano, salt and a squeeze of lemon.',
      'Air fryer at 190 °C for 14–18 min, turning halfway, until the thickest part reaches 74 °C (no pink inside). Rest 3 min, then slice.',
      'Serve with lemon juice and chopped parsley.',
    ],
    tips: [
      'Cook 3 portions at once; keep in the fridge up to 3 days.',
      'Cool cooked rice within 1 hour, refrigerate, and reheat until steaming hot.',
    ],
    gut: 'Very gentle: white rice, soft carrots, lean protein, no onion or garlic.',
  }),
  R({
    id: 'hake_potatoes_beans',
    name: 'Pescada no forno com batata e feijão-verde',
    en: 'Baked hake with potatoes & green beans',
    slots: ['lunch', 'dinner'],
    phase: 1,
    methods: ['oven', 'air fryer', 'saucepan'],
    minutes: 30,
    ingredients: [
      { food: 'hake', g: 200, role: 'protein' },
      { food: 'potatoes', g: 280, role: 'carb' },
      { food: 'green_beans', g: 80, role: 'veg' },
      { food: 'olive_oil', g: 8, role: 'fat' },
      { food: 'lemon', g: 10, role: 'season' },
      { food: 'parsley', g: 3, role: 'season' },
    ],
    steps: [
      'Potatoes: peel, cut into chunks and boil in salted water 15–18 min until a knife slides in.',
      'Green beans: boil from frozen for 6–8 min.',
      'Hake: put the fillets (from frozen is fine) on a tray, season with salt, lemon and parsley.',
      'Bake at 200 °C for 15–20 min (frozen) or 10–12 min (thawed). Air fryer: 190 °C for 12–15 min.',
      'Drizzle the measured olive oil over the plate at the end.',
    ],
    tips: ['A classic Portuguese plate. Cod works the same way.'],
    gut: 'Lean white fish and boiled potato are some of the easiest foods to digest.',
  }),
  R({
    id: 'arroz_de_frango',
    name: 'Arroz de frango (sem cebola nem alho)',
    en: 'Portuguese chicken rice (no onion/garlic)',
    slots: ['lunch', 'dinner'],
    phase: 1,
    methods: ['saucepan'],
    minutes: 35,
    batch: true,
    ingredients: [
      { food: 'chicken_breast', g: 160, role: 'protein' },
      { food: 'rice_white', g: 75, role: 'carb' },
      { food: 'carrots', g: 60, role: 'veg' },
      { food: 'red_pepper', g: 30, role: 'veg', minPhase: 2 },
      { food: 'olive_oil', g: 7, role: 'fat' },
      { food: 'paprika', g: 1, role: 'season' },
      { food: 'bay_leaf', g: 0.2, role: 'season' },
      { food: 'chives', g: 3, role: 'season' },
      { food: 'garlic_for_oil', g: 0, role: 'season' },
    ],
    steps: [
      'Optional garlic flavour: warm the measured oil with 1 sliced garlic clove for 1–2 min, then remove ALL the garlic pieces.',
      'Brown the chicken cubes in the oil for 4–5 min. Add the diced carrot (and pepper from phase 2), colorau, bay leaf and salt; cook 2 min.',
      'Stir in the rice for 1 min, then add hot water (2½ times the rice volume).',
      'Simmer covered on low 15–17 min, until the rice is tender and still a little moist.',
      'Finish with chopped chives (green part) or parsley.',
    ],
    tips: ['Makes a great 3-portion batch for lunches.'],
    gut: 'Garlic-infused oil and chives give the flavour; the fructans stay out.',
  }),
  R({
    id: 'pork_potatoes_courgette',
    name: 'Lombo de porco grelhado com batata cozida e curgete',
    en: 'Grilled pork loin with boiled potatoes & courgette',
    slots: ['lunch', 'dinner'],
    phase: 1,
    methods: ['pan', 'saucepan'],
    minutes: 25,
    ingredients: [
      { food: 'pork_loin', g: 160, role: 'protein' },
      { food: 'potatoes', g: 250, role: 'carb' },
      { food: 'courgette', g: 100, role: 'veg' },
      { food: 'olive_oil', g: 5, role: 'fat' },
      { food: 'lemon', g: 10, role: 'season' },
      { food: 'paprika', g: 1, role: 'season' },
      { food: 'bay_leaf', g: 0.2, role: 'season' },
    ],
    steps: [
      'Trim visible fat. Marinate the steaks with lemon juice, colorau, bay leaf and salt for 10+ min (overnight is fine).',
      'Boil the peeled potatoes 15–20 min.',
      'Heat a non-stick pan until very hot and grill the steaks 2–3 min per side (cooked through, 63–70 °C).',
      'In the same pan, cook the courgette slices (peeled in phase 1) with the measured oil for 4–5 min.',
    ],
    tips: ['Thin "bifanas" cuts cook in 3–4 minutes.'],
    gut: 'Lean cut, measured oil, soft courgette.',
  }),
  R({
    id: 'beef_rice_skillet',
    name: 'Arroz de carne picada com cenoura e curgete',
    en: 'Lean beef mince with rice, carrot & courgette',
    slots: ['lunch', 'dinner'],
    phase: 1,
    methods: ['pan', 'saucepan'],
    minutes: 25,
    batch: true,
    ingredients: [
      { food: 'beef_mince_lean', g: 140, role: 'protein' },
      { food: 'rice_white', g: 70, role: 'carb' },
      { food: 'carrots', g: 60, role: 'veg' },
      { food: 'courgette', g: 60, role: 'veg' },
      { food: 'soy_sauce', g: 10, role: 'season' },
      { food: 'paprika', g: 1, role: 'season' },
      { food: 'cumin', g: 0.5, role: 'season' },
    ],
    steps: [
      'Cook the rice (see the chicken & rice recipe).',
      'Brown the mince in a dry non-stick pan for 5–6 min, breaking it up. Pour off any fat.',
      'Add the grated carrot and diced courgette; cook 5 min.',
      'Season with soy sauce, colorau and cumin. Serve over the rice.',
    ],
    tips: ['Freezes well in portions.'],
    gut: 'No added oil: the mince brings its own fat.',
  }),
  R({
    id: 'cod_potatoes_egg',
    name: 'Bacalhau cozido com batata, cenoura e ovo',
    en: 'Boiled cod with potatoes, carrots & egg',
    slots: ['lunch', 'dinner'],
    phase: 1,
    methods: ['saucepan'],
    minutes: 30,
    ingredients: [
      { food: 'cod_desalted', g: 180, role: 'protein' },
      { food: 'eggs', g: 52, role: 'protein' },
      { food: 'potatoes', g: 250, role: 'carb' },
      { food: 'carrots', g: 100, role: 'veg' },
      { food: 'olive_oil', g: 8, role: 'fat' },
      { food: 'parsley', g: 3, role: 'season' },
    ],
    steps: [
      'Thaw the cod in the fridge overnight.',
      'Boil the peeled potatoes and carrots for 12 min.',
      'Add the cod and the egg (in its shell) and cook 8–10 min more.',
      'Drain, peel the egg, and drizzle the measured olive oil and parsley over everything.',
    ],
    tips: ['Weigh the oil: "bacalhau cozido" is usually drowned in it.'],
    gut: 'Soft, simple and very Portuguese.',
  }),
  R({
    id: 'turkey_rice_beans',
    name: 'Bifes de peru com arroz e feijão-verde',
    en: 'Turkey steaks with rice & green beans',
    slots: ['lunch', 'dinner'],
    phase: 1,
    methods: ['pan', 'saucepan'],
    minutes: 20,
    ingredients: [
      { food: 'turkey_steaks', g: 170, role: 'protein' },
      { food: 'rice_white', g: 70, role: 'carb' },
      { food: 'green_beans', g: 80, role: 'veg' },
      { food: 'olive_oil', g: 5, role: 'fat' },
      { food: 'lemon', g: 10, role: 'season' },
      { food: 'oregano', g: 1, role: 'season' },
    ],
    steps: [
      'Cook the rice and boil the green beans from frozen (6–8 min).',
      'Season the turkey with salt, oregano and lemon.',
      'Cook in a non-stick pan with the measured oil, 3 min per side, until white throughout.',
      'Deglaze the pan with a splash of water and lemon juice and pour over.',
    ],
    tips: ['Turkey steaks are thin: they are ready fast and stay juicy if you do not overcook them.'],
    gut: 'Lean and simple.',
  }),
  R({
    id: 'oven_tortilla',
    name: 'Tortilha de batata no forno (sem cebola)',
    en: 'Oven-baked potato tortilla (no onion)',
    slots: ['lunch', 'dinner'],
    phase: 1,
    methods: ['oven', 'air fryer'],
    minutes: 40,
    batch: true,
    ingredients: [
      { food: 'eggs', g: 104, role: 'protein' },
      { food: 'egg_whites', g: 150, role: 'protein' },
      { food: 'potatoes', g: 220, role: 'carb' },
      { food: 'courgette', g: 70, role: 'veg' },
      { food: 'olive_oil', g: 5, role: 'fat' },
      { food: 'chives', g: 3, role: 'season' },
    ],
    steps: [
      'Slice the potatoes thinly and toss with half the oil and salt. Bake at 200 °C for 15 min (air fryer 190 °C, 12 min) until soft.',
      'Whisk the eggs and whites with salt and chives; stir in the potatoes and diced courgette.',
      'Pour into an oiled oven dish (or an air-fryer-safe tin) and bake at 180 °C for 15–20 min until set in the middle.',
    ],
    tips: ['Cut into portions: good cold the next day.'],
    gut: 'Eggs and potatoes without the usual onion and deep-frying oil.',
  }),
  R({
    id: 'salmon_potatoes_spinach',
    name: 'Salmão no air fryer com batata, batata-doce e espinafres',
    en: 'Air-fryer salmon with potatoes, sweet potato & spinach',
    slots: ['lunch', 'dinner'],
    phase: 2,
    methods: ['air fryer', 'saucepan'],
    minutes: 25,
    ingredients: [
      { food: 'salmon', g: 130, role: 'protein' },
      { food: 'potatoes', g: 150, role: 'carb' },
      { food: 'sweet_potato', g: 100, role: 'veg' },
      { food: 'spinach', g: 100, role: 'veg' },
      { food: 'lemon', g: 10, role: 'season' },
    ],
    steps: [
      'Cube both potatoes and air-fry at 200 °C for 18–22 min, shaking twice (no oil needed with a non-stick basket).',
      'Season the salmon with salt and lemon. Air-fry at 180 °C for 9–12 min, skin side down.',
      'Warm the spinach from frozen in a pan with a splash of water, 4–5 min. Squeeze out excess water.',
    ],
    tips: ['Salmon is rich: no extra oil on this plate.'],
    gut: 'Oily fish in a moderate portion; sweet potato kept to 100 g.',
  }),
  R({
    id: 'chicken_pasta_courgette',
    name: 'Massa com frango e curgete',
    en: 'Chicken & courgette pasta',
    slots: ['lunch', 'dinner'],
    phase: 2,
    methods: ['saucepan', 'pan'],
    minutes: 20,
    ingredients: [
      { food: 'chicken_breast', g: 150, role: 'protein' },
      { food: 'pasta', g: 70, role: 'carb' },
      { food: 'courgette', g: 100, role: 'veg' },
      { food: 'olive_oil', g: 7, role: 'fat' },
      { food: 'lemon', g: 10, role: 'season' },
      { food: 'parsley', g: 3, role: 'season' },
      { food: 'garlic_for_oil', g: 0, role: 'season' },
    ],
    steps: [
      'Boil the pasta in salted water as per the pack (about 10 min). Keep a cup of the cooking water.',
      'Optional: flavour the oil with a garlic clove, then remove all pieces.',
      'Cook the chicken strips in the oil 5–6 min, add the courgette and cook 4 min more.',
      'Toss with the pasta, lemon zest and juice, parsley and a splash of pasta water.',
    ],
    tips: ['If wheat bothers you, use rice or gluten-free pasta.'],
    gut: 'Pasta portion kept moderate (wheat has fructans).',
  }),
  R({
    id: 'bolognese_no_onion',
    name: 'Esparguete à bolonhesa sem cebola nem alho',
    en: 'Spaghetti bolognese without onion or garlic',
    slots: ['lunch', 'dinner'],
    phase: 2,
    methods: ['saucepan'],
    minutes: 30,
    batch: true,
    ingredients: [
      { food: 'beef_mince_lean', g: 130, role: 'protein' },
      { food: 'pasta', g: 70, role: 'carb' },
      { food: 'passata', g: 100, role: 'veg' },
      { food: 'carrots', g: 60, role: 'veg' },
      { food: 'olive_oil', g: 3, role: 'fat' },
      { food: 'oregano', g: 1, role: 'season' },
      { food: 'bay_leaf', g: 0.2, role: 'season' },
    ],
    steps: [
      'Brown the mince in a non-stick pan with the oil, 5–6 min. Pour off any fat.',
      'Add finely grated carrot, cook 3 min. Add the passata, oregano, bay leaf and salt.',
      'Simmer covered on low for 15 min (add a splash of water if needed).',
      'Serve over the cooked pasta.',
    ],
    tips: ['Check the passata has no onion or garlic in the ingredients.'],
    gut: 'Tomato can aggravate reflux: eat this at lunch rather than late at night.',
  }),
  R({
    id: 'tuna_rice_bowl',
    name: 'Taça de atum com arroz, pepino e cenoura',
    en: 'Tuna rice bowl with cucumber & carrot',
    slots: ['lunch', 'dinner'],
    phase: 2,
    methods: ['no cooking (leftover rice)'],
    minutes: 10,
    ingredients: [
      { food: 'tuna_water', g: 110, role: 'protein' },
      { food: 'rice_white', g: 70, role: 'carb' },
      { food: 'cucumber', g: 80, role: 'veg' },
      { food: 'carrots', g: 50, role: 'veg' },
      { food: 'olive_oil', g: 5, role: 'fat' },
      { food: 'soy_sauce', g: 10, role: 'season' },
      { food: 'lemon', g: 10, role: 'season' },
    ],
    steps: [
      'Use rice cooked earlier (reheated until steaming, or chilled).',
      'Drain the tuna well. Dice the cucumber and grate the carrot.',
      'Assemble the bowl and dress with soy sauce, lemon and the measured oil.',
    ],
    tips: ['Good for work lunches in a lunchbox.'],
    gut: 'Raw vegetables from phase 2; keep them to this portion at first.',
  }),
  R({
    id: 'chicken_potatoes_broccoli',
    name: 'Frango e batatas no air fryer com brócolos',
    en: 'Air-fryer chicken & potatoes with broccoli',
    slots: ['lunch', 'dinner'],
    phase: 2,
    methods: ['air fryer', 'saucepan'],
    minutes: 30,
    ingredients: [
      { food: 'chicken_breast', g: 170, role: 'protein' },
      { food: 'potatoes', g: 250, role: 'carb' },
      { food: 'broccoli', g: 75, role: 'veg' },
      { food: 'olive_oil', g: 5, role: 'fat' },
      { food: 'paprika', g: 1, role: 'season' },
      { food: 'oregano', g: 1, role: 'season' },
    ],
    steps: [
      'Cut the potatoes into wedges, toss with the measured oil, colorau and salt.',
      'Air-fry at 200 °C for 10 min, then add the seasoned chicken and cook 14–18 min more at 190 °C, turning halfway (chicken to 74 °C).',
      'Boil or steam the broccoli florets 4–5 min.',
    ],
    tips: ['Florets only: the stalks are harder on the gut.'],
    gut: 'Broccoli kept to 75 g of florets.',
  }),

  // ───────────── Snacks ─────────────
  R({
    id: 'rice_cakes_tuna',
    name: 'Tortitas de arroz com atum',
    en: 'Rice cakes with tuna',
    slots: ['snack'],
    phase: 1,
    methods: ['no cooking'],
    minutes: 5,
    ingredients: [
      { food: 'tuna_water', g: 80, role: 'protein' },
      { food: 'rice_cakes', g: 30, role: 'carb' },
      { food: 'cucumber', g: 60, role: 'veg' },
      { food: 'lemon', g: 5, role: 'season' },
    ],
    steps: ['Drain the tuna, season with lemon and pepper, and pile it on the rice cakes with cucumber slices.'],
    gut: 'Simple and low in fat.',
  }),
  R({
    id: 'boiled_eggs_fruit',
    name: 'Ovos cozidos e kiwi',
    en: 'Boiled eggs & kiwi',
    slots: ['snack'],
    phase: 1,
    methods: ['saucepan'],
    minutes: 12,
    ingredients: [
      { food: 'eggs', g: 104, role: 'protein' },
      { food: 'kiwi', g: 75, role: 'carb' },
    ],
    steps: ['Boil the eggs 9–10 min, cool in cold water and peel.', 'Boil 6 at a time: they keep 5 days in the fridge in their shells.'],
    gut: '',
  }),
  R({
    id: 'turkey_toast_snack',
    name: 'Tosta de fiambre de peru',
    en: 'Turkey ham toast',
    slots: ['snack'],
    phase: 1,
    methods: ['toaster'],
    minutes: 5,
    ingredients: [
      { food: 'turkey_ham', g: 60, role: 'protein' },
      { food: 'bread', g: 56, role: 'carb' },
      { food: 'cucumber', g: 40, role: 'veg' },
    ],
    steps: ['Toast the bread, fill with turkey ham and cucumber slices.'],
    tips: ['Read the ham label for lactose, onion and garlic.'],
    gut: '',
  }),
  R({
    id: 'banana_peanut',
    name: 'Banana com manteiga de amendoim (pré-treino)',
    en: 'Banana with peanut butter (pre-workout)',
    slots: ['snack'],
    phase: 1,
    methods: ['no cooking'],
    minutes: 2,
    ingredients: [
      { food: 'banana', g: 120, role: 'carb' },
      { food: 'peanut_butter', g: 15, role: 'fat' },
    ],
    steps: ['Slice the banana and spread the peanut butter on top. Eat 60–90 min before training.'],
    gut: 'Low protein: the planner makes up for it at lunch and dinner.',
  }),
  R({
    id: 'carrot_soup_eggs',
    name: 'Creme de cenoura e curgete com ovos cozidos',
    en: 'Carrot & courgette soup with boiled eggs',
    slots: ['snack'],
    phase: 1,
    methods: ['saucepan'],
    minutes: 30,
    batch: true,
    ingredients: [
      { food: 'eggs', g: 104, role: 'protein' },
      { food: 'carrots', g: 120, role: 'veg' },
      { food: 'courgette', g: 80, role: 'veg' },
      { food: 'potatoes', g: 50, role: 'carb' },
      { food: 'olive_oil', g: 3, role: 'fat' },
    ],
    steps: [
      'Batch of 4: boil 500 g carrots, 300 g peeled courgette and 200 g potato in 1.2 L salted water for 20 min.',
      'Blend until smooth and stir in 12 g olive oil.',
      'Serve one bowl (≈ 300 ml) with the boiled eggs.',
    ],
    tips: ['Portuguese-style soup without onion. Keeps 4 days in the fridge and freezes well.', 'A bowl of soup before dinner is a great hunger-killer.'],
    gut: 'Cooked, blended vegetables are the gentlest way to add fibre.',
  }),
  R({
    id: 'lf_yogurt_bowl',
    name: 'Iogurte sem lactose com mirtilos e aveia',
    en: 'Lactose-free yogurt with blueberries & oats',
    slots: ['snack', 'breakfast'],
    phase: 3,
    methods: ['no cooking'],
    minutes: 3,
    tags: ['test-food'],
    ingredients: [
      { food: 'lf_yogurt', g: 250, role: 'protein' },
      { food: 'oats', g: 20, role: 'carb' },
      { food: 'blueberries', g: 60, role: 'fruit' },
    ],
    steps: ['Mix and eat. Only use this once you have tested lactose-free yogurt (see the Gut tab).'],
    gut: 'Test food: start with half a pot on a calm day and wait 2–3 days before judging.',
  }),
];

export const RECIPE_BY_ID = Object.fromEntries(RECIPES.map((r) => [r.id, r]));

export function getRecipe(id) {
  return RECIPE_BY_ID[id] || null;
}
